"""initial_schema

Revision ID: 7a325dd858b0
Revises:
Create Date: 2026-07-25 22:06:31.854047

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a325dd858b0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "tasks", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("tasks", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_index(
        "ix_tasks_user_status_created",
        "tasks",
        ["user_id", "status", "created_at"],
        unique=False,
    )
    op.create_foreign_key(None, "tasks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index("ix_tasks_user_status_created", table_name="tasks")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.alter_column("tasks", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "tasks", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
